name: CI

on:
  push:
    branches: 
      - develop
      - main
  pull_request:
    branches: 
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest # Ensure your Gitea runner is configured with this label or Change it to your runner label
    env: 
      RUNNER_TOOL_CACHE: /toolcache

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Type check
        run: npm run build
        env:
          CI: true
